// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBueXJqKSJbe8x3Wayag6Xwmn4lU6AWpdw',
    appId: '1:1083708969304:web:280d4633436d725e75152d',
    messagingSenderId: '1083708969304',
    projectId: 'moveeasy-478313',
    authDomain: 'moveeasy-478313.firebaseapp.com',
    storageBucket: 'moveeasy-478313.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiNj0IePDDUiliJYP5jxmVgCiw8qhylcI',
    appId: '1:1083708969304:android:55f2d055fa6d7b2b75152d',
    messagingSenderId: '1083708969304',
    projectId: 'moveeasy-478313',
    storageBucket: 'moveeasy-478313.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0DaQsUO3qF-BW04B2lE33dADXrsQRNqM',
    appId: '1:1083708969304:ios:788c14d0b03fe53375152d',
    messagingSenderId: '1083708969304',
    projectId: 'moveeasy-478313',
    storageBucket: 'moveeasy-478313.firebasestorage.app',
    iosBundleId: 'com.example.moveeasyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0DaQsUO3qF-BW04B2lE33dADXrsQRNqM',
    appId: '1:1083708969304:ios:788c14d0b03fe53375152d',
    messagingSenderId: '1083708969304',
    projectId: 'moveeasy-478313',
    storageBucket: 'moveeasy-478313.firebasestorage.app',
    iosBundleId: 'com.example.moveeasyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBueXJqKSJbe8x3Wayag6Xwmn4lU6AWpdw',
    appId: '1:1083708969304:web:3027689c6c055d4175152d',
    messagingSenderId: '1083708969304',
    projectId: 'moveeasy-478313',
    authDomain: 'moveeasy-478313.firebaseapp.com',
    storageBucket: 'moveeasy-478313.firebasestorage.app',
  );
}
